basePath: /
host: 127.0.0.1:3000
info:
  contact: {}
  description: zbp restful api document
  title: zbp api
  version: "1.0"
paths:
  /api/getAllPlugin:
    get:
      description: 获取所有插件的状态
      parameters:
      - default: 0
        description: 群号
        in: query
        name: group_id
        type: integer
      responses: {}
  /api/getBotList:
    get:
      description: 获取机器人qq号
      responses: {}
  /api/getFriendList:
    get:
      description: 获取好友列表
      parameters:
      - default: 123456
        description: 机器人qq号
        in: query
        name: self_id
        required: true
        type: integer
      responses: {}
  /api/getGroupList:
    get:
      description: 获取群列表
      parameters:
      - default: 123456
        description: 机器人qq号
        in: query
        name: self_id
        required: true
        type: integer
      responses: {}
  /api/getPlugin:
    get:
      description: 获取某个插件的状态
      parameters:
      - default: 0
        description: 群号
        in: query
        name: group_id
        type: integer
      - default: antibuse
        description: 插件名
        in: query
        name: name
        type: string
      responses: {}
  /api/updatePluginStatus:
    post:
      description: 更改某一个插件状态
      parameters:
      - default: 0
        description: 群号
        in: formData
        name: group_id
        type: integer
      - default: aireply
        description: 插件名
        in: formData
        name: name
        required: true
        type: string
      - default: true
        description: 插件状态
        in: formData
        name: status
        type: boolean
      responses: {}
swagger: "2.0"
